function daysFromNow(n) {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

function daysAgo(n) {
  return new Date(Date.now() - n * 86400000).toISOString()
}

// Real MARUG partners 2026-2027, sourced from Gmail/Drive
export const MOCK_PARTNERS = [
  {
    id: 'real-1',
    company: 'Omnicom (OMC)',
    sector: 'Consultancy',
    contactName: 'Jessica de Vries',
    contactEmail: 'jessica.devries@omc.com',
    partnershipTier: 'Main Partner',
    status: 'Deal gesloten',
    events: ['Inhousetour', 'Recruitment Days'],
    financialValue: 1750,
    priority: 'Hoog',
    followUpDate: daysFromNow(30),
    lastContactDate: '2026-09-16',
    notes: 'Partnership €1.750 excl. btw, looptijd 20 apr 2026 – 20 apr 2027. Vacature online geplaatst. Direct mailing al gebruikt bij vorige vacature. Inhousetour nog te plannen.',
    createdAt: daysAgo(160),
    updatedAt: '2026-09-16T08:56:09Z',
  },
  {
    id: 'real-2',
    company: 'ON. digital',
    sector: 'Media',
    contactName: 'Johan Siefkes',
    contactEmail: 'johan@ondigital.nl',
    partnershipTier: 'Event Partner',
    status: 'Deal gesloten',
    events: ['Conference'],
    financialValue: 750,
    priority: 'Hoog',
    followUpDate: daysFromNow(60),
    lastContactDate: '2026-09-18',
    notes: 'Contract getekend door beide partijen op 18 sep 2026. Driehoeksbel gehad met Johan. Definitief getekend contract retour ontvangen.',
    createdAt: daysAgo(14),
    updatedAt: '2026-09-18T12:20:07Z',
  },
  {
    id: 'real-3',
    company: 'Diepzeekonijn',
    sector: 'Media',
    contactName: 'Matthijs',
    contactEmail: 'matthijs@diepzeekonijn.nl',
    partnershipTier: 'Eenmalig',
    status: 'Voorstel verstuurd',
    events: ['Commercial Night'],
    financialValue: 500,
    priority: 'Hoog',
    followUpDate: daysFromNow(7),
    lastContactDate: '2026-09-17',
    notes: 'Samenwerking van inmiddels 10 jaar. Twee contractversies gestuurd: basis + versie met social media post (Instagram 1.800 volgers). Wacht op keuze + tekst over 10-jarig jubileum voor website.',
    createdAt: daysAgo(21),
    updatedAt: '2026-09-17T11:28:09Z',
  },
  {
    id: 'real-4',
    company: 'DVJ Research Group',
    sector: 'Consultancy',
    contactName: 'Nicole Engels',
    contactEmail: 'nicole.engels@dvjresearchgroup.com',
    partnershipTier: 'Event Partner',
    status: 'Voorstel verstuurd',
    events: ['Speeddate', 'Inhousetour', 'Commercial Night'],
    financialValue: 500,
    priority: 'Hoog',
    followUpDate: daysFromNow(8),
    lastContactDate: '2026-09-21',
    notes: 'Meerdere opties aangeboden: Bedrijvenavond €500 (meeste interesse), Speeddate €750, Gen Z panel €400, Research challenge €1.000, Partnership €1.850, Inhousetour €100/student. Antwoord bedrijvenavond gevraagd vóór 2 oktober.',
    createdAt: daysAgo(30),
    updatedAt: '2026-09-21T11:01:32Z',
  },
  {
    id: 'real-5',
    company: 'Deloitte',
    sector: 'Consultancy',
    contactName: 'M. ter Schure',
    contactEmail: 'MterSchure@deloitte.nl',
    partnershipTier: 'Main Partner',
    status: 'In gesprek',
    events: ['Conference', 'Speeddate'],
    financialValue: 1850,
    priority: 'Hoog',
    followUpDate: daysFromNow(5),
    lastContactDate: '2026-09-10',
    notes: 'Teams-meeting uitgenodigd op 10 sep 2026. Samenwerking MARUG – Deloitte besproken.',
    createdAt: daysAgo(20),
    updatedAt: '2026-09-10T11:27:57Z',
  },
  {
    id: 'real-6',
    company: 'CIC (RUG)',
    sector: 'Overig',
    contactName: 'Randolf Kobus',
    contactEmail: 'r.kobus@rug.nl',
    partnershipTier: 'Eenmalig',
    status: 'In gesprek',
    events: ['Recruitment Days'],
    financialValue: 400,
    priority: 'Gemiddeld',
    followUpDate: daysFromNow(4),
    lastContactDate: '2026-09-18',
    notes: 'Customer Insights Center RUG. Bijpraten na pauze. Meeting afgesproken voor maandag 28 of dinsdag 29 september op de RUG om 15:00. 9 nieuwe stageplekken beschikbaar.',
    createdAt: daysAgo(40),
    updatedAt: '2026-09-18T11:37:49Z',
  },
  {
    id: 'real-7',
    company: 'Zavhy',
    sector: 'Tech',
    contactName: 'Ryan / Zeeshan',
    contactEmail: 'Ryan@zavhy.com',
    partnershipTier: 'Vacature Partner',
    status: 'Voorstel verstuurd',
    events: ['Recruitment Days'],
    financialValue: 400,
    priority: 'Gemiddeld',
    followUpDate: daysFromNow(7),
    lastContactDate: '2026-09-24',
    notes: 'Meeting 22 sep gehad. Opties gestuurd voor promotie stage via MARUG. Ryan gaf aan dat 2026 lastig is, maar overzicht van kandidatenpool gestuurd om hen te overtuigen.',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(0),
  },
  {
    id: 'real-8',
    company: 'Kaartje2Go',
    sector: 'Retail',
    contactName: 'Kay-Lee',
    contactEmail: 'kay-lee@kaartje2go.nl',
    partnershipTier: 'Event Partner',
    status: 'Benaderd',
    events: [],
    financialValue: 500,
    priority: 'Gemiddeld',
    followUpDate: daysFromNow(5),
    lastContactDate: '2026-09-22',
    notes: 'Interesse getoond in samenwerking. Brochure gedeeld via Drive-link (te groot voor bijlage). Wacht op reactie.',
    createdAt: daysAgo(7),
    updatedAt: '2026-09-22T09:27:12Z',
  },
  {
    id: 'real-9',
    company: 'beDRIJFNAT',
    sector: 'Overig',
    contactName: '',
    contactEmail: 'info@bedrijfnat.nl',
    partnershipTier: 'Eenmalig',
    status: 'Voorstel verstuurd',
    events: [],
    financialValue: 300,
    priority: 'Gemiddeld',
    followUpDate: daysFromNow(5),
    lastContactDate: '2026-09-22',
    notes: 'Eerder bij hen langs geweest met Luc. Leuk gesprek gehad. Voorstel verstuurd op 22 sep. Wacht op reactie.',
    createdAt: daysAgo(30),
    updatedAt: '2026-09-22T09:18:02Z',
  },
  {
    id: 'real-10',
    company: 'Zonneplan',
    sector: 'Tech',
    contactName: 'Erwin',
    contactEmail: 'erwin@zonneplan.nl',
    partnershipTier: 'Eenmalig',
    status: 'Afgewezen',
    events: [],
    financialValue: 0,
    priority: 'Laag',
    followUpDate: null,
    lastContactDate: '2026-09-22',
    notes: 'In augustus aangegeven dat samenwerking er nu niet in zit. Op 22 sep tip gestuurd over CIC van de RUG. Volgend academisch jaar opnieuw proberen.',
    createdAt: daysAgo(60),
    updatedAt: '2026-09-22T08:46:23Z',
  },
]
