function daysFromNow(n) {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

function daysAgo(n) {
  return new Date(Date.now() - n * 86400000).toISOString()
}

export const MOCK_PARTNERS = [
  {
    id: 'mock-1',
    company: 'Tomorrowmen',
    sector: 'Consultancy',
    contactName: 'Roman Solarz',
    contactEmail: 'hallo@tomorrowmen.nl',
    partnershipTier: 'Main Partner',
    status: 'Voorstel verstuurd',
    events: ['Conference', 'Recruitment Days'],
    financialValue: 1000,
    priority: 'Hoog',
    followUpDate: daysFromNow(3),
    lastContactDate: daysFromNow(-7),
    notes: 'Geïnteresseerd in AI course (maandagavond). Wil podiumtijd, niet alleen logo.',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
  },
  {
    id: 'mock-2',
    company: 'Harvest Digital',
    sector: 'Tech',
    contactName: 'Lisa van Dijk',
    contactEmail: '',
    partnershipTier: 'Event Partner',
    status: 'Benaderd',
    events: ['Recruitment Days'],
    financialValue: 500,
    priority: 'Gemiddeld',
    followUpDate: daysFromNow(0),
    lastContactDate: daysFromNow(-3),
    notes: 'Al zichtbaar op homepage als banner. Peilen of ze meer willen.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-3',
    company: 'Belsimpel',
    sector: 'Retail',
    contactName: 'Mark Hoeksma',
    contactEmail: '',
    partnershipTier: 'Main Partner',
    status: 'Deal gesloten',
    events: ['Conference', 'Recruitment Days', 'Inhousetour'],
    financialValue: 2500,
    priority: 'Hoog',
    followUpDate: daysFromNow(60),
    lastContactDate: daysFromNow(-5),
    notes: 'Traineeship en parttime vacatures actief. Jaarlijkse partner.',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: 'mock-4',
    company: 'KPMG',
    sector: 'Finance',
    contactName: 'Sofie Janssen',
    contactEmail: 'sofie.janssen@kpmg.nl',
    partnershipTier: 'Main Partner',
    status: 'In gesprek',
    events: ['Speeddate', 'Conference'],
    financialValue: 2000,
    priority: 'Hoog',
    followUpDate: daysFromNow(-1),
    lastContactDate: daysFromNow(-2),
    notes: 'Zoekt toegang tot finance-afstudeerders. Budget besproken.',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(3),
  },
  {
    id: 'mock-5',
    company: 'Coolblue',
    sector: 'Retail',
    contactName: '',
    contactEmail: '',
    partnershipTier: 'Eenmalig',
    status: 'Lead',
    events: ['Commercial Night'],
    financialValue: 300,
    priority: 'Laag',
    followUpDate: daysFromNow(7),
    lastContactDate: null,
    notes: 'Potentieel via netwerk Stijn.',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'mock-6',
    company: 'Spotify',
    sector: 'Tech',
    contactName: 'Emma Groot',
    contactEmail: 'e.groot@spotify.com',
    partnershipTier: 'Event Partner',
    status: 'Deal gesloten',
    events: ['Commercial Night', 'Inhousetour'],
    financialValue: 1500,
    priority: 'Hoog',
    followUpDate: daysFromNow(90),
    lastContactDate: daysFromNow(-10),
    notes: 'Employer branding gericht op creatieve studenten.',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
  },
  {
    id: 'mock-7',
    company: 'Deloitte',
    sector: 'Consultancy',
    contactName: 'Jan de Vries',
    contactEmail: 'j.devries@deloitte.nl',
    partnershipTier: 'Main Partner',
    status: 'Afgewezen',
    events: [],
    financialValue: 0,
    priority: 'Laag',
    followUpDate: null,
    lastContactDate: daysFromNow(-20),
    notes: 'Budget bevroren voor dit jaar. Volgend jaar opnieuw proberen.',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(20),
  },
  {
    id: 'mock-8',
    company: 'RTL Nederland',
    sector: 'Media',
    contactName: 'Anna Bakker',
    contactEmail: 'a.bakker@rtl.nl',
    partnershipTier: 'Vacature Partner',
    status: 'Voorstel verstuurd',
    events: ['Recruitment Days', 'Speeddate'],
    financialValue: 750,
    priority: 'Gemiddeld',
    followUpDate: daysFromNow(5),
    lastContactDate: daysFromNow(-4),
    notes: 'Interesse in media/communicatie studenten.',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
  },
]
